import React, {useEffect, useMemo, useRef, useState} from 'react';
import Layout from '@theme/Layout';
import Heading from '@theme/Heading';

import styles from './sandbox.module.css';

type TaggedValue = {
  kind: string;
  value?: unknown;
  values?: TaggedValue[];
  fields?: Record<string, TaggedValue>;
  entries?: Array<{key: TaggedValue; value: TaggedValue}>;
};

type SessionResult = {
  kind: 'session-result';
  hasValue: boolean;
  value: TaggedValue | null;
  text: string;
  retainedCount: number;
};

type FScriptModule = {
  run(source: string, options?: unknown): TaggedValue;
  createSession(options?: unknown): unknown;
  resetSession(session: unknown): unknown;
  submit(session: unknown, source: string): SessionResult;
  formatValue(value: unknown): string;
};

type OutputState =
  | {status: 'idle'; text: string; detail?: string}
  | {status: 'ok'; text: string; detail?: string}
  | {status: 'error'; text: string; detail?: string};

type Example = {
  label: string;
  source: string;
  shared: string;
};

const examples: Example[] = [
  {
    label: 'Values',
    source: `let add x y = x + y
let numbers = [1; 2; 3; 4]
let total = List.fold add 0 numbers
total`,
    shared: `let inc x = x + 1`,
  },
  {
    label: 'Imports',
    source: `import "shared.fss" as Shared

[<export>] let answer = Shared.inc 41
answer`,
    shared: `let inc x = x + 1`,
  },
  {
    label: 'Session',
    source: `let twice x = x * 2`,
    shared: `let inc x = x + 1`,
  },
];

const defaultOutput: OutputState = {
  status: 'idle',
  text: 'Ready.',
};

function stringifyTagged(value: unknown) {
  return JSON.stringify(
    value,
    (_key, item) => (typeof item === 'bigint' ? `${item.toString()}n` : item),
    2,
  );
}

function formatError(error: unknown) {
  if (typeof error === 'object' && error !== null) {
    const err = error as {
      kind?: string;
      phase?: string;
      message?: string;
      span?: {start?: {file?: string; line?: number; column?: number}};
    };
    if (err.kind === 'fscript-error') {
      const position = err.span?.start;
      const location =
        position && typeof position.line === 'number'
          ? ` ${position.file ?? '<source>'}:${position.line}:${position.column ?? 1}`
          : '';
      return {
        text: `${err.phase ?? 'host'} error${location}`,
        detail: err.message ?? 'FScript error',
      };
    }
    if ('message' in err && typeof err.message === 'string') {
      return {text: 'JavaScript host error', detail: err.message};
    }
  }
  return {text: 'JavaScript host error', detail: String(error)};
}

export default function Sandbox() {
  const [fscript, setFscript] = useState<FScriptModule | null>(null);
  const [source, setSource] = useState(examples[0].source);
  const [sharedSource, setSharedSource] = useState(examples[0].shared);
  const [mode, setMode] = useState<'program' | 'session'>('program');
  const [output, setOutput] = useState<OutputState>(defaultOutput);
  const [history, setHistory] = useState<string[]>([]);
  const sessionRef = useRef<unknown>(null);

  const options = useMemo(
    () => ({
      rootDirectory: '/',
      entryFile: '/main.fss',
      sources: {
        '/shared.fss': sharedSource,
      },
    }),
    [sharedSource],
  );

  useEffect(() => {
    let cancelled = false;

    async function loadRuntime() {
      try {
        // The module is generated by npm scripts before Docusaurus starts or builds.
        const module = (await import('../generated/fscript/Library.js')) as FScriptModule;
        if (!cancelled) {
          setFscript(module);
          sessionRef.current = module.createSession(options);
        }
      } catch (error) {
        if (!cancelled) {
          const formatted = formatError(error);
          setOutput({status: 'error', text: formatted.text, detail: formatted.detail});
        }
      }
    }

    loadRuntime();

    return () => {
      cancelled = true;
    };
  }, [options]);

  function selectExample(label: string) {
    const selected = examples.find((item) => item.label === label) ?? examples[0];
    setSource(selected.source);
    setSharedSource(selected.shared);
    setOutput(defaultOutput);
    setHistory([]);
    if (fscript) {
      sessionRef.current = fscript.createSession({
        rootDirectory: '/',
        entryFile: '/main.fss',
        sources: {'/shared.fss': selected.shared},
      });
    }
  }

  function runProgram() {
    if (!fscript) {
      setOutput({status: 'idle', text: 'FScript is still loading.'});
      return;
    }

    try {
      const value = fscript.run(source, options);
      setOutput({status: 'ok', text: fscript.formatValue(value), detail: stringifyTagged(value)});
    } catch (error) {
      const formatted = formatError(error);
      setOutput({status: 'error', text: formatted.text, detail: formatted.detail});
    }
  }

  function ensureSession() {
    if (!fscript) {
      return null;
    }
    if (!sessionRef.current) {
      sessionRef.current = fscript.createSession(options);
    }
    return sessionRef.current;
  }

  function submitToSession() {
    if (!fscript) {
      setOutput({status: 'idle', text: 'FScript is still loading.'});
      return;
    }

    const session = ensureSession();
    if (!session) {
      return;
    }

    try {
      const result = fscript.submit(session, source);
      const text = result.hasValue ? result.text : `Stored ${result.retainedCount} declaration(s).`;
      setOutput({
        status: 'ok',
        text,
        detail: result.value ? stringifyTagged(result.value) : undefined,
      });
      setHistory((items) => [`> ${source}\n${text}`, ...items].slice(0, 8));
    } catch (error) {
      const formatted = formatError(error);
      setOutput({status: 'error', text: formatted.text, detail: formatted.detail});
    }
  }

  function resetSession() {
    if (fscript && sessionRef.current) {
      fscript.resetSession(sessionRef.current);
    }
    setHistory([]);
    setOutput({status: 'idle', text: 'Session reset.'});
  }

  return (
    <Layout title="FScript Sandbox" description="Run FScript in the browser with the Fable JavaScript runtime.">
      <main className={styles.page}>
        <section className={styles.shell}>
          <div className={styles.header}>
            <div>
              <Heading as="h1" className={styles.title}>
                FScript Sandbox
              </Heading>
              <p className={styles.subtitle}>Browser execution powered by the Fable JavaScript facade.</p>
            </div>
            <div className={styles.toolbar}>
              <label className={styles.selectLabel}>
                Example
                <select className={styles.select} onChange={(event) => selectExample(event.target.value)}>
                  {examples.map((example) => (
                    <option key={example.label} value={example.label}>
                      {example.label}
                    </option>
                  ))}
                </select>
              </label>
              <div className={styles.segmented} role="group" aria-label="Execution mode">
                <button
                  type="button"
                  className={mode === 'program' ? styles.segmentActive : styles.segment}
                  onClick={() => setMode('program')}>
                  Program
                </button>
                <button
                  type="button"
                  className={mode === 'session' ? styles.segmentActive : styles.segment}
                  onClick={() => setMode('session')}>
                  Session
                </button>
              </div>
            </div>
          </div>

          <div className={styles.workspace}>
            <section className={styles.editorPanel} aria-label="Main source">
              <div className={styles.panelHeader}>
                <span>Main</span>
                <button
                  type="button"
                  className={styles.primaryButton}
                  onClick={mode === 'program' ? runProgram : submitToSession}
                  disabled={!fscript}>
                  {mode === 'program' ? 'Run' : 'Submit'}
                </button>
              </div>
              <textarea
                className={styles.editor}
                spellCheck={false}
                value={source}
                onChange={(event) => setSource(event.target.value)}
              />
            </section>

            <section className={styles.editorPanel} aria-label="Virtual import source">
              <div className={styles.panelHeader}>
                <span>/shared.fss</span>
                {mode === 'session' ? (
                  <button type="button" className={styles.secondaryButton} onClick={resetSession}>
                    Reset
                  </button>
                ) : null}
              </div>
              <textarea
                className={styles.importEditor}
                spellCheck={false}
                value={sharedSource}
                onChange={(event) => setSharedSource(event.target.value)}
              />

              <div className={styles.output} data-status={output.status}>
                <div className={styles.outputHeader}>Output</div>
                <pre className={styles.outputText}>{output.text}</pre>
                {output.detail ? <pre className={styles.outputDetail}>{output.detail}</pre> : null}
              </div>
            </section>
          </div>

          {mode === 'session' && history.length > 0 ? (
            <section className={styles.history} aria-label="Session history">
              <div className={styles.outputHeader}>Session History</div>
              {history.map((item, index) => (
                <pre key={`${index}-${item.length}`} className={styles.historyItem}>
                  {item}
                </pre>
              ))}
            </section>
          ) : null}
        </section>
      </main>
    </Layout>
  );
}
