# This file was generated by https://github.com/magnusopera/fscript/blob/main/.github/scripts/generate-homebrew-tap
class Fscript${FSCRIPT_SUFFIX} < Formula
  desc "Embeddable F#/ML-style scripting language and CLI"
  homepage "https://github.com/magnusopera/fscript"
  version "${FSCRIPT_VERSION}"

  if OS.mac? && Hardware::CPU.intel?
    url "${FSCRIPT_DARWIN_X64_URL}"
    sha256 "${FSCRIPT_DARWIN_X64_SHA256}"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "${FSCRIPT_DARWIN_ARM64_URL}"
    sha256 "${FSCRIPT_DARWIN_ARM64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "${FSCRIPT_LINUX_X64_URL}"
    sha256 "${FSCRIPT_LINUX_X64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "${FSCRIPT_LINUX_ARM64_URL}"
    sha256 "${FSCRIPT_LINUX_ARM64_SHA256}"
  end

  def install
    bin.install "fscript" => name
  end

  test do
    system bin/name, "--help"
  end
end
